VLZ-5722: update cert-manager dependency to sub chart
VolumezTech/helm-csi pull request #48
Opened 2023-03-02 15:05 UTC by avivlevitski-vlz

update cert-manager dependency to sub chart and change cert-manager namespace to unique name

2023-03-05 09:27 UTC, ayalgenzer approved these changes

2023-03-05 16:30 UTC, nkorobko requested changes

2023-03-05 16:34 UTC, avivlevitski-vlz commented on .gitignore
> +charts/*
right.
Helm is downloading all the sub-charts into it

2023-03-05 16:38 UTC, avivlevitski-vlz commented on charts/volumez-csi/Chart.yaml
> +    version: v1.11.0
changing the version it's the dev or everyone else who wishes to update this dependency on volumez-csi chart

2023-03-06 16:07 UTC, nkorobko approved these changes

2023-03-06 16:07 UTC, merged